name: selenium_tutorial
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - uses: actions/checkout@v3
        if: success() || failure()

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=tests/reports/" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}

      - name: Run tests
        run: |
          python main.py

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: reports/allure-report

      - name: Deploy Allure report to GitHub Pages
        if: success()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAGES_TOKEN }}
          publish_dir: reports/allure-report
          publish_branch: gh-pages
          keep_files: false
